#Generates the MRC instances
#- hosts: localhost
#  vars_files:
#    - host_vars/nectar.yaml
#  gather_facts: true
#
#  roles:
#    - role: openstack-common
#    - role: openstack-volume
#    - role: openstack-security-group
#    - role: openstack-instance

#Begins to set up the CouchDB database 
#- hosts: couchDB
#  vars_files:
#    - host_vars/couchDB.yaml
#  gather_facts: true
#
#  roles:
#    - role: common
#     - role: docker    
#    - role: volumes
#    - role: setupCouchDB


# Perform CouchDB configuration on slave nodes
#- hosts: couchDB:!Masternode
#  vars_files:
#    - host_vars/couchDB.yaml
#  gather_facts: true
#
#  roles:
#    - role: couchDB_slave_nodes_setup


# Sets up a tweets harvester
#- hosts: TwitterHarvester
#  vars_files:
#    - host_vars/twitterHarverster.yaml
#  gather_facts: true
#
#  roles:
#    - role: setupTwitHarvester


# Sets up the web app
- hosts: Webapp
  vars_files:
  - host_vars/webapp.yaml
  gather_facts: true

  roles:
    - role: common
    - role: docker    
    - role: volumes
    - role: setupWebapp
