# COMP90024 - Assignment 2 - team 60
#
#  Junhong Liu         - Student ID: 1084997 - Melbourne
#  Justin Beaconsfield - Student ID: 761885  - Melbourne
#  Callum Dowling      - Student ID: 1009257 - Palmwoods
#  Soham Swapnil Dighe - Student ID: 1219439 - Melbourne
#  Samy Allouache      - Student ID: 1210426 - Melbourne
---
#Create an instance on the MRC
- name: Create a new instance
  openstack.cloud.server:
    name: '{{item.name}}'
    image: '{{instance_image}}'
    key_name: '{{instance_key_name}}'
    flavor: '{{instance_flavor}}'
    availability_zone: '{{availability_zone}}'
    security_groups: '{{sg_names}}'
    volumes: '{{item.volumes}}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- ansible.builtin.debug:
    msg: " Instance {{item.openstack.name}} has been created. IP adress is {{item.openstack.public_v4}}"
  loop: '{{ os_instance.results}}'
  when: item.openstack is defined

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined


# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: '{{item.openstack.public_v4}}'
    groups: COMP90024
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

      