# COMP90024 - Assignment 2 - team 60
#
#  Junhong Liu         - Student ID: 1084997 - Melbourne
#  Justin Beaconsfield - Student ID: 761885  - Melbourne
#  Callum Dowling      - Student ID: 1009257 - Palmwoods
#  Soham Swapnil Dighe - Student ID: 1219439 - Melbourne
#  Samy Allouache      - Student ID: 1210426 - Melbourne
---
# Clone source code repository
- name: Clone the code repository into home directory
  ansible.builtin.git:
    repo: https://github.com/sohamdighe14/COMP90024-A2.git
    dest: /home/ubuntu/gitRepo
  become: true

# Create Docker config directory
- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'

# Build Docker image for tweet harvester
- name: Build an image and push it to local repo
  docker_image:
    build:
      path: '/home/ubuntu/gitRepo/TweetHarvestor/'
      pull: yes
    name: tweet_harvester_image
    source: build
  become: yes

# Stop existing Docker containers for Twitter Harvesters and remove them (if any)
- name: Stop Twitter Harvester Docker container
  become: yes
  docker_container:
    name: harvesting_container
    state: absent

# Create new docker container for Twitter Harvester and start container
- name: Create and start Twitter Harvester Docker container
  become: yes
  docker_container:
    name: harvesting_container
    image: tweet_harvester_image
    state: started
    pull: false
    recreate: true