# COMP90024 - Assignment 2 - team 60
#
#  Junhong Liu         - Student ID: 1084997 - Melbourne
#  Justin Beaconsfield - Student ID: 761885  - Melbourne
#  Callum Dowling      - Student ID: 1009257 - Palmwoods
#  Soham Swapnil Dighe - Student ID: 1219439 - Melbourne
#  Samy Allouache      - Student ID: 1210426 - Melbourne
---
#Create volumes from vars 
- name: Create volume(s) on the MRC
  openstack.cloud.volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

#Get a list of volume Ids from the value of os_volume
- name: Create a list of volume Ids
  ansible.builtin.set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [item.id] }}'
  loop: '{{ os_vol.results }}'

- ansible.builtin.debug:
    msg: "Volume {{os_vol_ids}} has been created"