---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker

#Connection to the MRC
ansible_user: ubuntu
ansible_ssh_private_key_file: ./slave1samy.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#couchDB info
user: admin
pass: adminpass
cookie: a192aeb9904e6590849337933b000c99


