---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker

#Connection to the MRC
ansible_user: ubuntu
ansible_ssh_private_key_file: ./sdighe1.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'