# COMP90024 - Assignment 2 - team 60
#
#  Junhong Liu         - Student ID: 1084997 - Melbourne
#  Justin Beaconsfield - Student ID: 761885  - Melbourne
#  Callum Dowling      - Student ID: 1009257 - Palmwoods
#  Soham Swapnil Dighe - Student ID: 1219439 - Melbourne
#  Samy Allouache      - Student ID: 1210426 - Melbourne
---
# Clone source code repository
- name: Clone the code repository into home directory
  ansible.builtin.git:
    repo: https://github.com/sohamdighe14/COMP90024-A2.git
    dest: /home/ubuntu/gitRepo
    version: main
  become: true

# Create Docker config directory
- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'


# Stop webapp container
- name: Stop webapp Docker container
  become: yes
  docker_container:
    name: flask_app
    state: absent

- name: Stop nginx Docker container
  become: yes
  docker_container:
    name: nginx
    state: absent

# Start nginx and webapp
- name: Run docker compose
  tags: 'webapp'
  become: yes
  docker_compose: 
    remove_images: local
    project_src: "/home/ubuntu/gitRepo/Webapp"
    pull: yes
    build: yes
    nocache: yes
    state: present
    remove_orphans: yes
    recreate: always


- name: install nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: copy nginx file
  become: yes
  copy: 
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root

- name: restart nginx
  become: yes
  shell:
    cmd: systemctl restart nginx
