---
# Clone source code repository
- name: Clone the code repository into home directory
  ansible.builtin.git:
    repo: https://github.com/sohamdighe14/COMP90024-A2.git
    dest: /home/ubuntu/gitRepo
    version: webapp_deployment
  become: true

# Create Docker config directory
- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'


# Stop webapp container
- name: Stop webapp Docker container
  become: yes
  docker_container:
    name: script
    state: absent

# Stop deployment container
- name: Stop deployment Docker container
  become: yes
  docker_container:
    name: deployment
    state: absent

# Start nginx and webapp
- name: Run docker compose
  tags: 'webapp'
  become: yes
  docker_compose:
    project_src: "/home/ubuntu/gitRepo/Webapp"
    pull: false
    build: yes
    state: present
    remove_orphans: no
    recreate: always


#- name: Copy website files to the server's document root
#  copy:
#    src: "{{ app_root }}"
#    dest: "{{ document_root }}"
#    mode: preserve

#- name: Apply Nginx template
#  ansible.builtin.template:
#    src: files/nginx.conf.j2
#    dest: /etc/nginx/sites-available/default
#  notify: Restart Nginx

#- name: Enable new site
#  ansible.builtin.file:
#    src: /etc/nginx/sites-available/default
#    dest: /etc/nginx/sites-enabled/default
#    state: link
#  notify: Restart Nginx

#- name: Allow all access to tcp port 80
#  community.general.ufw:
#    rule: allow
#    port: '80'
#    proto: tcp