# COMP90024 - Assignment 2 - team 60
#
#  Junhong Liu         - Student ID: 1084997 - Melbourne
#  Justin Beaconsfield - Student ID: 761885  - Melbourne
#  Callum Dowling      - Student ID: 1009257 - Palmwoods
#  Soham Swapnil Dighe - Student ID: 1219439 - Melbourne
#  Samy Allouache      - Student ID: 1210426 - Melbourne
---
- name: Restart a CouchDB docker container
  become: yes
  community.docker.docker_container:
    name: couchDB
    image: "ibmcom/couchdb3:3.0.0"
    state: started
    restart: yes
    ports:
     # Publish couchDB port 5984 as host port 5984
     - "5984:5984"
     # 
     - "4369:4369"
     # 
     - "9100-9200:9100-9200"
    volumes:
      - /var/lib/docker
    pull: yes
    env:
        COUCHDB_USER: "{{ user }}"
        COUCHDB_PASSWORD: "{{ pass }}"
        COUCHDB_SECRET: "{{ cookie }}"
        ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""