# COMP90024 - Assignment 2 - team 60
#
#  Junhong Liu         - Student ID: 1084997 - Melbourne
#  Justin Beaconsfield - Student ID: 761885  - Melbourne
#  Callum Dowling      - Student ID: 1009257 - Palmwoods
#  Soham Swapnil Dighe - Student ID: 1219439 - Melbourne
#  Samy Allouache      - Student ID: 1210426 - Melbourne

services:
  app:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "5000:5000"

  nginx:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "80:80"
