services:
  app:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "5000:5000"

  nginx:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "80:80"
